---
- name: Add Elastic repo public signing key
  rpm_key: 
      key: "{{logstash_gpgkey}}"
      state: present 
  tags: 
     - install

- stat: "path=/etc/yum.repos.d/logstash-{{logstash_version}}.repo"
  register: repo_st
- name: Add Logstash repo
  when: repo_st.stat.exists is defined and not repo_st.stat.exists
  template: 
      src: logstash.repo.j2 
      dest: "/etc/yum.repos.d/logstash-{{logstash_version}}.repo" 
      mode: 0644
  tags: 
     - install

- name: Install logstash
  yum:
    name: logstash
    update_cache: yes
    state: present
  tags: 
     - install

