---
- name: RedHat - Ensure Java is installed
  yum: name={{ java }} state=latest
  when: ansible_os_family == 'RedHat'
  
- name: Debian - Ensure Java is installed
  apt: name={{ java }} state=present update_cache=yes force=yes
  when: ansible_os_family == 'Debian'